### ISSUE TITLE
How to run the code ?

### ISSUE THREAD

**Issue by vifulnirala** [MahadISL/Chart-Decoder-An-Automatic-System-for-Data-Extraction-from-Chart-Images#1]

**Comment by MahadISL** [comment]
- I haven't used a database for now on this project. I just wanted to make it functional and so I fetched and saved files(images) to different local folders I have created (as you will see in the code). You have to create those folders for your local machine or add a database.

- The trained models are not added to this repository because they are too big.

- Answer to your question: the main executable file is 'app.py'. You have to run this file after making the necessary changes to the code on your local machine.
